### ISSUE TITLE
No Example Visible

### ISSUE THREAD

**Issue by Nikhil1827** [genkernel/TreeView#10]
Hello,
I just came across this awesome library for which my requirements meet.
But I am not able to implement it, as there is no working example available on any site, also the example links that you have provided only show a 404 error. Can you provide a simple tutorial on how to use this?

**Comment by genkernel** [comment]
Hi.
Thanks for reporting the issue.

I noticed that XCode's workpsace was not committed due to being gitignored.
I created a new commit that fixed that. You should be able to open `Examples/TreeViewExample.xcworkspace` and run `TreeViewExample scheme` as shown below:
<img width="992" alt="Screen Shot 2022-10-20 at 3 41 46 🌙" src="https://user-images.githubusercontent.com/1649419/197073293-54de52ea-4393-4ff5-8e09-a2cdf7782acc.png">

I also added fetched Pods to the `Example` folder so that you do not need to run `pod install`.
lmk if you still experience problems when running examples.
